{"name": "test_list2", "status": "failed", "statusDetails": {"message": "AssertionError: assert [0, 1, 2] == [0, 1, [1, 2]]\n  At index 2 diff: 2 != [1, 2]\n  Use -v to get the full diff", "trace": "self = <tests.test_assertions.TestCollections object at 0x103556150>\n\n    def test_list2(self):\n>       assert [0,1,2] == [0,1,[1,2]]\nE       assert [0, 1, 2] == [0, 1, [1, 2]]\nE         At index 2 diff: 2 != [1, 2]\nE         Use -v to get the full diff\n\ntests/test_assertions.py:50: AssertionError"}, "start": 1591176793772, "stop": 1591176793773, "uuid": "c4060108-4e5b-489f-b614-47b3bd0fb7af", "historyId": "8799213a80221460c5a992f412a8b00c", "testCaseId": "1000bd682931fe10d0b28d18f717caa4", "fullName": "tests.test_assertions.TestCollections#test_list2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "subSuite", "value": "TestCollections"}, {"name": "host", "value": "LIUMENGJIAdeMacBook-Pro.local"}, {"name": "thread", "value": "78122-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}